name: Build pull request

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'OK to test') }}
    strategy:
      matrix:
        label:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.label }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          pixi-version: v0.63.2

      - name: Build packages
        shell: bash
        run: pixi run build-all
        env:
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true
          RATTLER_BUILD_COLOR: always
