name: Build and upload packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        label:
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.label }}
    env:
      DATA_FILE: data/failed-compatibility-${{ matrix.label }}.json
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 2
      - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          pixi-version: v0.63.2

      - name: Configure git
        run: pixi run configure-git

      - name: Build packages
        shell: bash
        run: pixi run build-all
        env:
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true
          RATTLER_BUILD_COLOR: always

      - name: Commit changes to failed-compatibility.json
        run: pixi run commit-changes ${{ env.DATA_FILE }}
        if: always()

      - name: Upload all packages
        shell: bash
        run: pixi run upload --channel modular-community
